# 1 - Introduction 

### Tableau à 1 dimension 

Le tableau Numpy est comparable à une séquence et il est plus puissant car :

- il prend moins de place en mémoire 
- il écrit des programmes plus rapides 
- il nous donne pus d'accès aux méthodes pour des calculs scientifiques



### Tableau à 2 dimensions

On travaille plus souvent dans un tableau à 2 dimensions et on le compare souvent à un tableau Excel 

*Exemple - on peut stocker les pixels d'une image avec la valeur entre 0 et 255*

### Tableau à 3 dimensions

La librairie Numpy à des méthodes et des attributs ("shape" est la plus utilisée)

ndarray.shape - il permet de voir la forme de la table (lignes, colonnes)

In [1]:
shape = (2,3)

**shape** est un tuple et un attribut immutable (package)

In [2]:
shape[0]

2

In [3]:
shape[1]

3

# 2 - Contenue de Numpy

### 2-1 Création d'un tableau

In [4]:
#Importer du module

import numpy as np

In [5]:
#Tableau à 1 dimension 

A = np.array([1,2,3])

In [6]:
#On peut voir la dimension de A
A.shape

(3,)

In [7]:
#On peut voir le nombre d'élément de A
A.size

3

On a des constructeur permettant d'initialiser nos tableaux avec certains nombres et certains dimensions

par exemple, on a la fonction 'np.zeros' qui initialise un tableau avec plein de zéros et ce qu'on a faire d'ndiquer dans notre fonction les dimensions qu'on va voir pour notre tableau (la forme ou le shape) 

In [8]:
#Construire un tableau avec des zéros

B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
#Un tableau contenant que des 1

C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
 C.size

12

In [11]:
#Matrice de valeurs aléatoires

np.random.seed(0) #pour conservé le nombre aléatoire
np.random.randn(3,4) #le plus utilisé

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [13]:
#Matrice identité

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#Création d'un tableau de dim1 réparti entre deux entiers avec le nombre éléments 

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
#un autre exemple de valeurs : 15 valeurs entre 1 et 5

np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [17]:
#Tableau à 1 dimension auquel on demande le pas entre le début et la fin 

np.arange(0,10,4)

array([0, 4, 8])

### 2-2 Choix des types de données

Quand on créer un tableau avec Numpy, on peut choisir quel type de donnée on veut avoir dans ce tableau avec '***dtype***'
Il y a beaucoup de type de données aux choix

*Exemple avec les bit*

*-plus on augmente le nombre de bit pouvant occupé nos données sur notre ordinateur et meilleur sera la précision avec une performance plus important(mais on aura un temps d'éxécution moins rapide)*



In [26]:
#Exemple pour le nombre "Pi"

np.float16

numpy.float16

In [27]:
np.pi

3.141592653589793

la méthode **linspace** permet de créer un tableau à 1 dimension qui a un début et une fin avec un quantité de nombre souhaité et réparti de façon égale entre le point de début et le point de fin

In [35]:
#Exemple 

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
np.arange(1,5,1)

array([1, 2, 3, 4])

On peut le type de donnée qui prend ou non de la place de la mémoire 

In [18]:
#exemple un choix d'un nombre à 16 bit

np.linspace(1,5,10,dtype=np.float16)

array([1.   , 1.444, 1.889, 2.334, 2.777, 3.223, 3.666, 4.11 , 4.555,
       5.   ], dtype=float16)

### 2-3 Manipulation de tableau 

On va commencer par créer 2 matrices

In [19]:
#Matrice contenant que des 0

A = np.zeros((3,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
#Matrice contenant que des 1

B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

On peut les assembler ces deux tableaux mais il existe plusieurs façon de le faire :
- **hastack** : les deux tableaux sont regroupés de façon horizontal
- **vastack** : les deux tableaux sont regroupés de façon vertical


*Ces deux méthodes peuvent être utile si on utilise les mathodes de régression par exemple*


In [21]:
#de façon horizontal

C1 = np.hstack((A,B)) 
C1

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [22]:
C1.shape

(3, 4)

In [23]:
#de façon vertical

C2 = np.vstack((A,B))
C2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
C2.shape

(6, 2)

On a une methode encore plus simple **concatenate**

In [52]:
#Une autre méthode

C3 = np.concatenate((A,B),axis=1)
C3

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

On peut remanipuler la forme du tableau avec "**reshape**"

In [28]:
#On redimensionne mon tableau 

C4 = C2.reshape((3,4))
C4

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

Cette fonction est très utile pour fairr des algorithmes 

In [29]:
D =  np.array([1,2,3])
D.shape

(3,)

In [30]:
D2 = D.reshape((A.shape[0],1))

In [31]:
D2

array([[1],
       [2],
       [3]])

In [32]:
D2.shape

(3, 1)

La méthode **squeeze** permet de faire disparaitre toute les dimension en 1

In [33]:
D3 = D2.squeeze()

In [34]:
D3.shape

(3,)

La méthode **ravel** permet de transformer notre tableau à n dimensions en 1 dimension et une méthode d'applatissement de données

In [36]:
C4.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])